package com.example.taimeietl.services;

import com.example.taimeietl.model.DrView;
import org.springframework.stereotype.Service;

import java.util.List;


public interface DrViewService {
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DR_VIEW
     *
     * @mbg.generated Tue Jun 08 17:19:45 CST 2021
     */
    int insert(DrView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DR_VIEW
     *
     * @mbg.generated Tue Jun 08 17:19:45 CST 2021
     */
    int insertSelective(DrView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DR_VIEW
     *
     * @mbg.generated Tue Jun 08 17:19:45 CST 2021
     */
    DrView selectByPrimaryKey(Integer id);
    List<DrView> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DR_VIEW
     *
     * @mbg.generated Tue Jun 08 17:19:45 CST 2021
     */
    int updateByPrimaryKeySelective(DrView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DR_VIEW
     *
     * @mbg.generated Tue Jun 08 17:19:45 CST 2021
     */
    int updateByPrimaryKey(DrView record);
}
