package com.example.taimeietl.model;

public class SourceInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOURCE_INFO.ID
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOURCE_INFO.SOURCE_NAME
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    private String sourceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOURCE_INFO.SOURCE_IP
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    private String sourceIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOURCE_INFO.SOURCE_PORT
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    private String sourcePort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOURCE_INFO.SOURCE_DB
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    private String sourceDb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOURCE_INFO.SOURCE_USER
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    private String sourceUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOURCE_INFO.SOURCE_PWD
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    private String sourcePwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOURCE_INFO.USEDB_NAME
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    private String usedbName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOURCE_INFO.MARK
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    private Integer mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOURCE_INFO.DB_TYPE
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    private String dbType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOURCE_INFO.SOURCE_TYPE
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    private Integer sourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SOURCE_INFO.cron
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    private String cron;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOURCE_INFO
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public SourceInfo(Integer id, String sourceName, String sourceIp, String sourcePort, String sourceDb, String sourceUser, String sourcePwd, String usedbName, Integer mark, String dbType, Integer sourceType, String cron) {
        this.id = id;
        this.sourceName = sourceName;
        this.sourceIp = sourceIp;
        this.sourcePort = sourcePort;
        this.sourceDb = sourceDb;
        this.sourceUser = sourceUser;
        this.sourcePwd = sourcePwd;
        this.usedbName = usedbName;
        this.mark = mark;
        this.dbType = dbType;
        this.sourceType = sourceType;
        this.cron = cron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOURCE_INFO
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public SourceInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOURCE_INFO.ID
     *
     * @return the value of SOURCE_INFO.ID
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOURCE_INFO.ID
     *
     * @param id the value for SOURCE_INFO.ID
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOURCE_INFO.SOURCE_NAME
     *
     * @return the value of SOURCE_INFO.SOURCE_NAME
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOURCE_INFO.SOURCE_NAME
     *
     * @param sourceName the value for SOURCE_INFO.SOURCE_NAME
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public void setSourceName(String sourceName) {
        this.sourceName = sourceName == null ? null : sourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOURCE_INFO.SOURCE_IP
     *
     * @return the value of SOURCE_INFO.SOURCE_IP
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public String getSourceIp() {
        return sourceIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOURCE_INFO.SOURCE_IP
     *
     * @param sourceIp the value for SOURCE_INFO.SOURCE_IP
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public void setSourceIp(String sourceIp) {
        this.sourceIp = sourceIp == null ? null : sourceIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOURCE_INFO.SOURCE_PORT
     *
     * @return the value of SOURCE_INFO.SOURCE_PORT
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public String getSourcePort() {
        return sourcePort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOURCE_INFO.SOURCE_PORT
     *
     * @param sourcePort the value for SOURCE_INFO.SOURCE_PORT
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public void setSourcePort(String sourcePort) {
        this.sourcePort = sourcePort == null ? null : sourcePort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOURCE_INFO.SOURCE_DB
     *
     * @return the value of SOURCE_INFO.SOURCE_DB
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public String getSourceDb() {
        return sourceDb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOURCE_INFO.SOURCE_DB
     *
     * @param sourceDb the value for SOURCE_INFO.SOURCE_DB
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public void setSourceDb(String sourceDb) {
        this.sourceDb = sourceDb == null ? null : sourceDb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOURCE_INFO.SOURCE_USER
     *
     * @return the value of SOURCE_INFO.SOURCE_USER
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public String getSourceUser() {
        return sourceUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOURCE_INFO.SOURCE_USER
     *
     * @param sourceUser the value for SOURCE_INFO.SOURCE_USER
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public void setSourceUser(String sourceUser) {
        this.sourceUser = sourceUser == null ? null : sourceUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOURCE_INFO.SOURCE_PWD
     *
     * @return the value of SOURCE_INFO.SOURCE_PWD
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public String getSourcePwd() {
        return sourcePwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOURCE_INFO.SOURCE_PWD
     *
     * @param sourcePwd the value for SOURCE_INFO.SOURCE_PWD
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public void setSourcePwd(String sourcePwd) {
        this.sourcePwd = sourcePwd == null ? null : sourcePwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOURCE_INFO.USEDB_NAME
     *
     * @return the value of SOURCE_INFO.USEDB_NAME
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public String getUsedbName() {
        return usedbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOURCE_INFO.USEDB_NAME
     *
     * @param usedbName the value for SOURCE_INFO.USEDB_NAME
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public void setUsedbName(String usedbName) {
        this.usedbName = usedbName == null ? null : usedbName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOURCE_INFO.MARK
     *
     * @return the value of SOURCE_INFO.MARK
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public Integer getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOURCE_INFO.MARK
     *
     * @param mark the value for SOURCE_INFO.MARK
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public void setMark(Integer mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOURCE_INFO.DB_TYPE
     *
     * @return the value of SOURCE_INFO.DB_TYPE
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public String getDbType() {
        return dbType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOURCE_INFO.DB_TYPE
     *
     * @param dbType the value for SOURCE_INFO.DB_TYPE
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public void setDbType(String dbType) {
        this.dbType = dbType == null ? null : dbType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOURCE_INFO.SOURCE_TYPE
     *
     * @return the value of SOURCE_INFO.SOURCE_TYPE
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public int getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOURCE_INFO.SOURCE_TYPE
     *
     * @param sourceType the value for SOURCE_INFO.SOURCE_TYPE
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public void setSourceType(int sourceType) {
        this.sourceType = sourceType;

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SOURCE_INFO.cron
     *
     * @return the value of SOURCE_INFO.cron
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public String getCron() {
        return cron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SOURCE_INFO.cron
     *
     * @param cron the value for SOURCE_INFO.cron
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    public void setCron(String cron) {
        this.cron = cron == null ? null : cron.trim();
    }
}