package com.example.taimeietl.model;

import java.util.Date;

public class TableInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE_INFO.ID
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE_INFO.TABLE_NAME
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE_INFO.TIME_FIELD
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    private String timeField;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE_INFO.MARK
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    private Integer mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE_INFO.QSQL
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    private String qsql;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE_INFO.FIELDS
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    private String fields;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE_INFO.START_TIME
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    private String startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE_INFO.END_TIME
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    private String endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE_INFO.TIME_MARK
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    private Integer timeMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE_INFO.SOURCE_ID
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    private Integer sourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE_INFO.PL
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    private Integer pl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE_INFO.MSSQL_TIMEFIELD
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    private String mssqlTimefield;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE_INFO.ODSTABLE_NAME
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    private String odstableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE_INFO.USEDB_NAME
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    private String usedbName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE_INFO.UPDATE_TIME
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_INFO
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    private Integer crsqlMark;

    private String descp;

    private Integer extractType;

        private String webserviceParamtable;

    private String webserviceParam;

    private String requestParam;

    private String webserviceCondition;

    private String xmlNodes;

    public Integer getExtractType() {
        return extractType;
    }

    public void setExtractType(Integer extractType) {
        this.extractType = extractType;
    }

    public String getDescp() {
        return descp;
    }

    public void setDescp(String descp) {
        this.descp = descp;
    }

    public Integer getCrsqlMark() {
        return crsqlMark;
    }

    public void setCrsqlMark(Integer crsqlMark) {
        this.crsqlMark = crsqlMark;
    }

    public String getWebserviceParamtable() {
        return webserviceParamtable;
    }

    public void setWebserviceParamtable(String webserviceParamtable) {
        this.webserviceParamtable = webserviceParamtable;
    }

    public String getWebserviceParam() {
        return webserviceParam;
    }

    public void setWebserviceParam(String webserviceParam) {
        this.webserviceParam = webserviceParam;
    }

    public TableInfo(Integer id, String tableName, String timeField, Integer mark, String qsql, String fields, String startTime, String endTime, Integer timeMark, Integer sourceId, Integer pl, String mssqlTimefield, String odstableName, String usedbName, String updateTime, Integer crsqlMark, String descp, Integer extractType
    , String webserviceParamtable, String webserviceParam,String requestParam,String webserviceCondition,String xmlNodes) {
        this.id = id;
        this.tableName = tableName;
        this.timeField = timeField;
        this.mark = mark;
        this.qsql = qsql;
        this.fields = fields;
        this.startTime = startTime;
        this.endTime = endTime;
        this.timeMark = timeMark;
        this.sourceId = sourceId;
        this.pl = pl;
        this.mssqlTimefield = mssqlTimefield;
        this.odstableName = odstableName;
        this.usedbName = usedbName;
        this.updateTime = updateTime;
        this.crsqlMark = crsqlMark;
        this.descp = descp;
        this.extractType = extractType;
        this.webserviceParamtable = webserviceParamtable;
        this.webserviceParam = webserviceParam;
        this.requestParam = requestParam;
        this.webserviceCondition = webserviceCondition;
        this.xmlNodes = xmlNodes;
    }

    public String getXmlNodes() {
        return xmlNodes;
    }

    public void setXmlNodes(String xmlNodes) {
        this.xmlNodes = xmlNodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_INFO
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */


    public TableInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE_INFO.ID
     *
     * @return the value of TABLE_INFO.ID
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE_INFO.ID
     *
     * @param id the value for TABLE_INFO.ID
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    public String getRequestParam() {
        return requestParam;
    }

    public void setRequestParam(String requestParam) {
        this.requestParam = requestParam;
    }

    public String getWebserviceCondition() {
        return webserviceCondition;
    }

    public void setWebserviceCondition(String webserviceCondition) {
        this.webserviceCondition = webserviceCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE_INFO.TABLE_NAME
     *
     * @return the value of TABLE_INFO.TABLE_NAME
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */

    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE_INFO.TABLE_NAME
     *
     * @param tableName the value for TABLE_INFO.TABLE_NAME
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE_INFO.TIME_FIELD
     *
     * @return the value of TABLE_INFO.TIME_FIELD
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public String getTimeField() {
        return timeField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE_INFO.TIME_FIELD
     *
     * @param timeField the value for TABLE_INFO.TIME_FIELD
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public void setTimeField(String timeField) {
        this.timeField = timeField == null ? null : timeField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE_INFO.MARK
     *
     * @return the value of TABLE_INFO.MARK
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public Integer getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE_INFO.MARK
     *
     * @param mark the value for TABLE_INFO.MARK
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public void setMark(Integer mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE_INFO.QSQL
     *
     * @return the value of TABLE_INFO.QSQL
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public String getQsql() {
        return qsql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE_INFO.QSQL
     *
     * @param qsql the value for TABLE_INFO.QSQL
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public void setQsql(String qsql) {
        this.qsql = qsql == null ? null : qsql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE_INFO.FIELDS
     *
     * @return the value of TABLE_INFO.FIELDS
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public String getFields() {
        return fields;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE_INFO.FIELDS
     *
     * @param fields the value for TABLE_INFO.FIELDS
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public void setFields(String fields) {
        this.fields = fields == null ? null : fields.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE_INFO.START_TIME
     *
     * @return the value of TABLE_INFO.START_TIME
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE_INFO.START_TIME
     *
     * @param startTime the value for TABLE_INFO.START_TIME
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE_INFO.END_TIME
     *
     * @return the value of TABLE_INFO.END_TIME
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE_INFO.END_TIME
     *
     * @param endTime the value for TABLE_INFO.END_TIME
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE_INFO.TIME_MARK
     *
     * @return the value of TABLE_INFO.TIME_MARK
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public Integer getTimeMark() {
        return timeMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE_INFO.TIME_MARK
     *
     * @param timeMark the value for TABLE_INFO.TIME_MARK
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public void setTimeMark(Integer timeMark) {
        this.timeMark = timeMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE_INFO.SOURCE_ID
     *
     * @return the value of TABLE_INFO.SOURCE_ID
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public Integer getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE_INFO.SOURCE_ID
     *
     * @param sourceId the value for TABLE_INFO.SOURCE_ID
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE_INFO.PL
     *
     * @return the value of TABLE_INFO.PL
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public Integer getPl() {
        return pl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE_INFO.PL
     *
     * @param pl the value for TABLE_INFO.PL
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public void setPl(Integer pl) {
        this.pl = pl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE_INFO.MSSQL_TIMEFIELD
     *
     * @return the value of TABLE_INFO.MSSQL_TIMEFIELD
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public String getMssqlTimefield() {
        return mssqlTimefield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE_INFO.MSSQL_TIMEFIELD
     *
     * @param mssqlTimefield the value for TABLE_INFO.MSSQL_TIMEFIELD
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public void setMssqlTimefield(String mssqlTimefield) {
        this.mssqlTimefield = mssqlTimefield == null ? null : mssqlTimefield.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE_INFO.ODSTABLE_NAME
     *
     * @return the value of TABLE_INFO.ODSTABLE_NAME
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public String getOdstableName() {
        return odstableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE_INFO.ODSTABLE_NAME
     *
     * @param odstableName the value for TABLE_INFO.ODSTABLE_NAME
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public void setOdstableName(String odstableName) {
        this.odstableName = odstableName == null ? null : odstableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE_INFO.USEDB_NAME
     *
     * @return the value of TABLE_INFO.USEDB_NAME
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public String getUsedbName() {
        return usedbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE_INFO.USEDB_NAME
     *
     * @param usedbName the value for TABLE_INFO.USEDB_NAME
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public void setUsedbName(String usedbName) {
        this.usedbName = usedbName == null ? null : usedbName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE_INFO.UPDATE_TIME
     *
     * @return the value of TABLE_INFO.UPDATE_TIME
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE_INFO.UPDATE_TIME
     *
     * @param updateTime the value for TABLE_INFO.UPDATE_TIME
     *
     * @mbg.generated Thu May 20 22:06:45 CST 2021
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }
}