package com.example.taimeietl.map;

import com.example.taimeietl.model.SourceInfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface SourceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOURCE_INFO
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOURCE_INFO
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    int insert(SourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOURCE_INFO
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    int insertSelective(SourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOURCE_INFO
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    List<SourceInfo> selectAll();
    SourceInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOURCE_INFO
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    int updateByPrimaryKeySelective(SourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SOURCE_INFO
     *
     * @mbg.generated Thu May 20 13:48:22 CST 2021
     */
    int updateByPrimaryKey(SourceInfo record);
}