package com.example.taimeietl.map;

import com.example.taimeietl.model.TableInfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
import java.util.Map;

@Mapper
public interface TableInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_INFO
     *
     * @mbg.generated Thu May 20 22:05:30 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_INFO
     *
     * @mbg.generated Thu May 20 22:05:30 CST 2021
     */
    int insert(TableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_INFO
     *
     * @mbg.generated Thu May 20 22:05:30 CST 2021
     */
    int insertSelective(TableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_INFO
     *
     * @mbg.generated Thu May 20 22:05:30 CST 2021
     */
    List<TableInfo> selectAll();
    TableInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_INFO
     *
     * @mbg.generated Thu May 20 22:05:30 CST 2021
     */
    int updateByPrimaryKeySelective(TableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_INFO
     *
     * @mbg.generated Thu May 20 22:05:30 CST 2021
     */
    int updateByPrimaryKey(TableInfo record);

    int createTable(int sid,int tid, int reCreate);

    int updateInit(TableInfo record);
    //    检查表是否存在
    int checkTable(String tableName);

    int handleTable(int sid,int tid ,int method,String partitionFields);

    List<TableInfo> selectAllBySid(int sid);

    void runSQL(String sql);
    List<Map<String,String>> selectSQL(String sql);
}