package com.example.taimeietl.map;

import com.example.taimeietl.model.TableInfo;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface TableInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_INFO
     *
     * @mbg.generated Thu May 20 22:05:30 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_INFO
     *
     * @mbg.generated Thu May 20 22:05:30 CST 2021
     */
    int insert(TableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_INFO
     *
     * @mbg.generated Thu May 20 22:05:30 CST 2021
     */
    int insertSelective(TableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_INFO
     *
     * @mbg.generated Thu May 20 22:05:30 CST 2021
     */
    List<TableInfo> selectAll();
    TableInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_INFO
     *
     * @mbg.generated Thu May 20 22:05:30 CST 2021
     */
    int updateByPrimaryKeySelective(TableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE_INFO
     *
     * @mbg.generated Thu May 20 22:05:30 CST 2021
     */
    int updateByPrimaryKey(TableInfo record);
}