DECLARE @STIME  datetime
SELECT @STIME = END_TIME  FROM ETL.DBO.TABLE_INFO WHERE ID = ${TABLE_ID}
    IF(CONVERT(NVARCHAR(100),DATEADD(DAY,${PL},@STIME),23)>CONVERT(NVARCHAR(100),GETDATE(),23))
BEGIN
IF (CONVERT(NVARCHAR(100),@STIME,23)<=CONVERT(NVARCHAR(100),GETDATE(),23))
BEGIN
UPDATE ETL.DBO.TABLE_INFO SET START_TIME = END_TIME WHERE ID = ${TABLE_ID} AND TIME_MARK = 1;
END
ELSE
BEGIN
UPDATE ETL.DBO.TABLE_INFO SET START_TIME = CONVERT(NVARCHAR(100),GETDATE(),23) WHERE ID = ${TABLE_ID} AND TIME_MARK = 1;
END
UPDATE ETL.DBO.TABLE_INFO SET END_TIME = CONVERT(NVARCHAR(100),DATEADD(DAY,1,GETDATE()),23) WHERE ID = ${TABLE_ID} AND TIME_MARK = 1;
END
ELSE
BEGIN
UPDATE ETL.DBO.TABLE_INFO SET START_TIME = END_TIME WHERE ID = ${TABLE_ID};
UPDATE ETL.DBO.TABLE_INFO SET END_TIME = CONVERT(NVARCHAR(100),DATEADD(DAY,${PL},END_TIME),23) WHERE ID = ${TABLE_ID} AND TIME_MARK = 1;
END
UPDATE ETL.DBO.TABLE_INFO SET UPDATE_TIME = CONVERT(NVARCHAR(100),GETDATE(),21) WHERE ID = ${TABLE_ID};